### ISSUE TITLE
Task list for Spoder Games

### ISSUE THREAD

**Issue by microlancer** [microlancer/godot-projects#5]
- [ ] Refactor world.tscn
- [ ] Create animated_player.tscn to reference from world
- [ ] Create animated_npc.tscn to reference from world
- [ ] Refactor battle.tscn to use the refactored parts

SKIP these for now: (Work on Puzzle Game?)

- [ ] Update merchant scene to use world, using the merchant npc
- [ ] Update shop to show 1 potion item for sale
- [ ] Update inventory to show 6 slots
- [ ] Use running animation + fade in/out for going to and leaving merchant
