### ISSUE TITLE
Task list for Max__17

### ISSUE THREAD

**Issue by microlancer** [microlancer/godot-projects#6]
- [ ] window resizing
- [ ] Graphical player stats
- [ ] New 2d enemies
- [ ] Enemy database
- [ ] Power/level progression
- [ ] drawing pad resizing
